# Generated by Django 4.1.4 on 2022-12-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password_hashed', models.CharField(max_length=200)),
                ('password_salt', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('primary_email', models.CharField(max_length=320)),
                ('secondary_email', models.CharField(max_length=320)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
