# Generated by Django 4.1.4 on 2022-12-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luvio_api', '0003_alter_useraccount_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
