# Generated by Django 4.1.4 on 2022-12-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0004_alter_userprofile_avatar_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_url",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
