# Generated by Django 4.1.4 on 2022-12-25 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0005_alter_userprofile_profile_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateAndTerritory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_code", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Suburb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("postcode", models.CharField(max_length=10)),
                (
                    "state_and_territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luvio_api.stateandterritory",
                    ),
                ),
            ],
        ),
    ]
