# Generated by Django 4.1.4 on 2022-12-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luvio_api', '0007_alter_registration_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
        migrations.AlterModelManagers(
            name='registration',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='username',
        ),
    ]
