# Generated by Django 4.1.4 on 2022-12-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0007_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
