# Generated by Django 4.1.4 on 2022-12-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luvio_api', '0009_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(default='invalidemail', max_length=320, unique=True),
        ),
    ]
