# Generated by Django 4.1.4 on 2022-12-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0011_alter_address_street_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_created",
            field=models.DateField(default="2022-12-26"),
        ),
    ]
