# Generated by Django 4.1.4 on 2022-12-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0012_userprofile_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_created",
            field=models.DateField(default="2022-12-27"),
        ),
    ]
