# Generated by Django 4.1.4 on 2022-12-27 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0013_alter_userprofile_date_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentProfilesAddresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("management_start_date", models.DateField()),
                ("management_end_date", models.DateField(blank=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luvio_api.address",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="luvio_api.userprofile",
                    ),
                ),
            ],
        ),
    ]
