# Generated by Django 4.1.4 on 2022-12-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0015_landlordprofilesaddresses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="landlordprofilesaddresses",
            old_name="end_date",
            new_name="ownership_end_date",
        ),
        migrations.RenameField(
            model_name="landlordprofilesaddresses",
            old_name="start_date",
            new_name="ownership_start_date",
        ),
    ]
