# Generated by Django 4.1.4 on 2022-12-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0017_profilesaddresses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilesaddresses",
            name="management_end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="profilesaddresses",
            name="management_start_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="profilesaddresses",
            name="move_in_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="profilesaddresses",
            name="move_out_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="profilesaddresses",
            name="ownership_end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="profilesaddresses",
            name="ownership_start_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="date_of_birth",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="mobile",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
