# Generated by Django 4.1.4 on 2022-12-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0018_alter_profilesaddresses_management_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_url",
        ),
    ]
