# Generated by Django 4.1.4 on 2022-12-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0021_userprofile_avatar_link_userprofile_profile_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="mobile",
        ),
    ]
