# Generated by Django 4.1.4 on 2022-12-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0022_remove_useraccount_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="mobile",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
