# Generated by Django 4.1.4 on 2022-12-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0024_alter_address_street_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_created",
            field=models.DateField(default="2022-12-29"),
        ),
    ]
