# Generated by Django 4.1.4 on 2023-01-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0026_alter_userprofile_date_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar_link",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_created",
            field=models.DateField(default="2023-01-07"),
        ),
    ]
