# Generated by Django 4.1.5 on 2023-01-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0027_remove_userprofile_avatar_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_link",
            field=models.ImageField(
                blank=True, default="avatars/default.jpg", upload_to="avatars/"
            ),
        ),
    ]
