# Generated by Django 4.1.5 on 2023-01-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0028_userprofile_avatar_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar_link",
        ),
    ]
