# Generated by Django 4.1.5 on 2023-01-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luvio_api", "0029_remove_userprofile_avatar_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatars/default.jpg", upload_to="avatars/"
            ),
        ),
    ]
