INVALID_EMAIL = "invalidemail"
TEXT_FIELD_MAX_LENGTH = 3000
EMAIL_FIELD_MAX_LENGTH = 320
NAME_FIELD_MAX_LENGTH = 100
PASSWORD_MAX_LENGTH = 320
PWD_SALT_MAX_LENGTH = 200
AU_MOBILE_MAX_LENGTH = 10

PROFILE_TYPES = {
    "tenant": "tenant",
    "agent": "agent",
    "landlord": "landlord",
}
