from .login_view import LoginView
from .profile_type_view import ProfileTypeView
from .registration_view import RegistrationView
from .user_account_view import UserAccountView, change_password
from .user_profile_view import UserProfileDetailView, UserProfileListView
from .address_view import get_address_suggestions
from .tenant_profile_address_view import TenantProfilesAddressesView
from .agent_profile_address_view import AgentProfilesAddressesView
from .landlord_profile_address_view import LandlordProfilesAddressesView
